(() => {
 const endpoint=String(window.LATTENSPECIALIST_BOOKING?.endpoint || '').replace(/\/$/,''),$=id=>document.getElementById(id);
 let token=sessionStorage.getItem('ls-team-session') || '',records=[],steps=[],waxes=[],generation=0;
 const escape=value=>String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const format=value=>value && /^\d{4}-\d{2}-\d{2}$/.test(value)?new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'long'}).format(new Date(value+'T12:00:00')):value || 'In overleg';
 function clear(){generation++;token='';sessionStorage.removeItem('ls-team-session');records=[];$('tasks').replaceChildren();$('dashboard').hidden=true;$('logout').hidden=true;$('login').hidden=false;$('loginForm').reset();}
 async function api(path,options={}){if(!endpoint)throw new Error('De werkplaats is nog niet verbonden.');const result=await fetch(endpoint+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},cache:'no-store'});const data=await result.json().catch(()=>({}));if(result.status===401)clear();if(!result.ok)throw new Error(data.message || 'Laden mislukt. Probeer opnieuw.');return data;}
 function render(){
  const query=$('search').value.toLowerCase().trim(),shown=records.filter(r=>[r.reference,r.customerName,r.material,r.package].join(' ').toLowerCase().includes(query));
  $('count').textContent=`${records.length} toegewezen opdracht${records.length===1?'':'en'}`;
  $('tasks').innerHTML=shown.map(r=>`<article class="task" data-reference="${escape(r.reference)}"><div class="task-head"><span class="task-code">${escape(r.reference)}</span><span class="pill">Stap ${r.currentStep}/8</span></div><h2>${escape(r.amount || 1)}× ${escape(r.material || 'Materiaal')}</h2><p>${escape(r.customerName)} · ${escape(r.package || 'Onderhoud')}</p><div class="details"><div><b>Verwacht klaar</b>${escape(format(r.expectedReady))}</div><div><b>Omstandigheden</b>${escape(r.conditions || 'Niet opgegeven')}</div></div><form><label>Voortgang<select name="currentStep">${steps.map((s,i)=>`<option value="${i+1}"${i+1===r.currentStep?' selected':''}${i+1<3 || i+1<r.currentStep || i+1>Math.max(3,r.currentStep+1)?' disabled':''}>${escape(s)}</option>`).join('')}</select></label><label>Wax voor deze beurt<select name="waxType">${waxes.map(w=>`<option${w===r.waxType?' selected':''}>${escape(w)}</option>`).join('')}</select></label><label>Werknotitie<textarea name="workNote" rows="3" maxlength="1000" placeholder="Uitgevoerde werkzaamheden en aandachtspunten">${escape(r.workNote)}</textarea></label><span class="hint">De werknotitie is alleen zichtbaar voor medewerkers en beheer. De klant ziet de voortgang en wax.</span><button class="primary" type="submit">Werk opslaan</button><div class="task-status" role="status"></div></form></article>`).join('') || '<div class="empty"><h2>Alles overzichtelijk.</h2><p>Er zijn op dit moment geen opdrachten die je hier kunt bekijken.</p></div>';
 }
 async function load(){const version=generation;const [session,tasks]=await Promise.all([api('/api/team/session'),api('/api/team/tasks')]);if(version!==generation || !token)return;records=tasks.records;steps=tasks.steps;waxes=tasks.waxes;$('greeting').textContent='WELKOM '+session.user.name.toUpperCase();$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;render();}
 $('loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;$('message').textContent='Aanmelden…';try{const values=Object.fromEntries(new FormData(event.target));const session=await api('/api/team/login',{method:'POST',body:JSON.stringify(values)});token=session.token;sessionStorage.setItem('ls-team-session',token);event.target.reset();await load();$('message').textContent='';}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}});
 $('tasks').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,card=form.closest('.task'),record=records.find(r=>r.reference===card.dataset.reference),message=form.querySelector('.task-status'),button=form.querySelector('button'),version=generation;button.disabled=true;message.textContent='Opslaan…';try{const values=Object.fromEntries(new FormData(form));const result=await api('/api/team/tasks/'+encodeURIComponent(record.reference),{method:'PATCH',body:JSON.stringify({...values,currentStep:Number(values.currentStep),revision:record.revision})});if(version!==generation)return;records=records.map(r=>r.reference===result.record.reference?result.record:r);render();$('message').textContent='Opgeslagen. De voortgang is bijgewerkt.';}catch(error){$('message').textContent=error.message;message.textContent=error.message;button.disabled=false;}});
 $('refresh').onclick=async()=>{const button=$('refresh');button.disabled=true;try{await load();$('message').textContent='';}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}};
 $('search').oninput=render;
 $('logout').onclick=async()=>{try{await api('/api/team/logout',{method:'POST'});}catch{}finally{clear();$('message').textContent='Je bent uitgelogd.';}};
 if(token)load().catch(error=>{clear();$('message').textContent=error.message;});
})();
