(() => {
 const endpoint=String(window.LATTENSPECIALIST_BOOKING?.endpoint||'').replace(/\/$/,''),$=id=>document.getElementById(id);
 let token=sessionStorage.getItem('ls-team-session')||'',records=[],steps=[],waxes=[],generation=0,scanner,hrmPin='',availabilityEntries=new Map(),availabilityMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),activeAvailabilityDate='';
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const format=value=>{const date=new Date(value);return value&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:'numeric',...(String(value).includes('T')?{hour:'2-digit',minute:'2-digit'}:{})}).format(date):value||'—';};
 function clear(){generation++;token='';hrmPin='';sessionStorage.removeItem('ls-team-session');records=[];$('tasks').replaceChildren();$('dashboard').hidden=true;$('logout').hidden=true;$('login').hidden=false;$('loginForm').reset();}
 async function api(path,options={}){if(!endpoint)throw new Error('De werkplaats is nog niet verbonden.');const result=await fetch(endpoint+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(options.headers||{})},cache:'no-store'});const data=await result.json().catch(()=>({}));if(result.status===401)clear();if(!result.ok){const error=new Error(data.message||'Laden mislukt.');error.status=result.status;throw error;}return data;}
 function setTab(name){document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==name);$('pageTitle').textContent={work:'Mijn werkzaamheden',routes:'Mijn routes',availability:'Mijn beschikbaarheid',hrm:'Mijn HRM'}[name];if(name==='routes')loadRoutes();if(name==='availability')loadAvailability();}
 function taskCard(r){return `<article class="task" data-reference="${escape(r.reference)}"><div class="task-head"><span class="task-code">${escape(r.reference)}</span><span class="pill">Stap ${r.currentStep}/8</span></div><h2>${escape(r.amount||1)}× ${escape(r.material||'Materiaal')}</h2><p>${escape(r.customerName)} · ${escape(r.package||'Onderhoud')}</p><div class="details"><div><b>Verwacht klaar</b>${escape(format(r.expectedReady))}</div><div><b>Omstandigheden</b>${escape(r.conditions||'Niet opgegeven')}</div></div><form><label>Voortgang<select name="currentStep">${steps.map((s,i)=>`<option value="${i+1}"${i+1===r.currentStep?' selected':''}${i+1<3||i+1<r.currentStep||i+1>Math.max(3,r.currentStep+1)?' disabled':''}>${escape(s)}</option>`).join('')}</select></label><label>Wax<select name="waxType">${waxes.map(w=>`<option${w===r.waxType?' selected':''}>${escape(w)}</option>`).join('')}</select></label><label>Interne werknotitie<textarea name="workNote" rows="3" maxlength="1000">${escape(r.workNote)}</textarea></label><button class="primary" type="submit">Werk opslaan</button><div class="task-status" role="status"></div></form></article>`;}
 function render(){const query=$('search').value.toLowerCase().trim(),shown=records.filter(r=>[r.reference,r.customerName,r.material,r.package].join(' ').toLowerCase().includes(query));$('count').textContent=`${records.length} toegewezen opdracht${records.length===1?'':'en'}`;$('tasks').innerHTML=shown.map(taskCard).join('')||'<div class="empty"><h2>Geen open opdrachten</h2><p>Scan een materiaalsticker of vernieuw het overzicht.</p></div>';}
 async function load(){const version=generation;const [session,tasks]=await Promise.all([api('/api/team/session'),api('/api/team/tasks')]);if(version!==generation||!token)return;records=tasks.records;steps=tasks.steps;waxes=tasks.waxes;$('greeting').textContent='WELKOM '+session.user.name.toUpperCase();$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;render();}
 function scanToken(value){const text=String(value||'').trim();if(/^[a-f0-9]{48}$/i.test(text))return text.toLowerCase();if(/^LSM-[A-F0-9]{6}$/i.test(text))return text.toUpperCase();try{const url=new URL(text);return new URLSearchParams(url.hash.replace(/^#/,'')).get('scan')||'';}catch{return text.match(/[a-f0-9]{48}/i)?.[0]?.toLowerCase()||text.match(/LSM-[A-F0-9]{6}/i)?.[0]?.toUpperCase()||'';}}
 function scanActions(status){const actions=[];if(status==='label_created')actions.push(['pickup_depart','Onderweg om op te halen'],['receive','Materiaal ontvangen']);if(status==='pickup_underway')actions.push(['receive','Materiaal ontvangen']);if(['received','paused'].includes(status))actions.push(['work_start','Start onderhoud']);if(status==='maintenance')actions.push(['work_pause','Pauzeer timer'],['work_complete','Onderhoud afronden']);if(status==='ready')actions.push(['delivery_depart','Onderweg terugbrengen'],['delivered','Afgeleverd']);if(status==='delivery_underway')actions.push(['delivered','Afgeleverd']);return actions;}
 async function openScan(value){const scan=scanToken(value);if(!scan){$('scanResult').innerHTML='<p class="error">Deze QR-code wordt niet herkend.</p>';return;}$('scanResult').innerHTML='<p>Materiaal laden…</p>';try{const result=await api('/api/team/operations/scan/'+scan),m=result.material,w=result.work;$('scanResult').innerHTML=`<article class="scan-detail" data-id="${escape(m.id)}" data-token="${escape(m.token)}"><div class="task-head"><strong>${escape(m.displayCode)}</strong><span class="pill">${escape(m.customerStatus)}</span></div><h2>${escape(m.kind)} · ${escape(w.package||m.package)}</h2><p><b>${escape(w.customerName)}</b>${w.address?`<br>${escape(w.address)}`:''}</p><div class="details"><div><b>Wax</b>${escape(w.waxType||'Nog bepalen')}</div><div><b>Omstandigheden</b>${escape(w.conditions||'Niet opgegeven')}</div></div>${w.notes?`<p class="note"><b>Klantnotitie</b><br>${escape(w.notes)}</p>`:''}<div class="scan-action-grid">${scanActions(m.internalStatus).map(([action,label])=>`<button type="button" data-scan-action="${action}" class="${action==='work_complete'||action==='receive'?'primary':''}">${label}</button>`).join('')||'<p>Geen volgende actie nodig.</p>'}</div></article>`;}catch(error){$('scanResult').innerHTML=`<p class="error">${escape(error.message)}</p>`;}}
 async function runScanAction(button){const card=button.closest('.scan-detail');button.disabled=true;try{await api(`/api/team/operations/materials/${card.dataset.id}/action`,{method:'POST',body:JSON.stringify({action:button.dataset.scanAction})});await openScan(card.dataset.token);await load();}catch(error){$('message').textContent=error.message;button.disabled=false;}}
 async function toggleScanner(){if(scanner){await scanner.stop().catch(()=>{});scanner.clear();scanner=null;$('qr-reader').hidden=true;$('startScanner').textContent='Camera openen';return;}if(!window.Html5Qrcode){$('message').textContent='De scanner kon niet worden geladen.';return;}$('qr-reader').hidden=false;scanner=new Html5Qrcode('qr-reader');try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},async decoded=>{await toggleScanner();openScan(decoded);});$('startScanner').textContent='Camera sluiten';}catch{$('qr-reader').hidden=true;scanner=null;$('message').textContent='Geef cameratoegang of voer de code handmatig in.';}}
 async function loadRoutes(){try{const result=await api('/api/team/operations/routes');$('routes').innerHTML=result.routes.map(route=>`<article class="route-card" data-route="${route.id}"><div class="task-head"><h3>${escape(format(route.route_date))}</h3><span class="pill">${escape(route.status)}</span></div><ol>${route.stops.map(stop=>`<li><b>${escape(stop.customer_name)}</b><br>${escape(stop.address)} · ${stop.item_count} item(s)<div class="stop-actions">${!stop.arrived_at?`<button type="button" data-route-action="arrive" data-stop="${stop.id}">Aangekomen</button>`:''}${stop.arrived_at&&!stop.departed_at?`<button type="button" data-route-action="depart" data-stop="${stop.id}">Opgehaald</button>`:''}${stop.departed_at?'<span>✓ opgehaald</span>':''}</div></li>`).join('')}</ol><div class="scan-action-grid">${route.status==='planned'?'<button type="button" class="primary" data-route-action="start">Start route & tijd</button>':''}${route.status==='active'?'<button type="button" class="primary" data-route-action="finish">Rond route af</button>':''}${route.maps_url?`<a class="primary route-link" href="${escape(route.maps_url)}" target="_blank" rel="noopener">Open routekaart</a>`:''}</div></article>`).join('')||'<p>Nog geen route toegewezen.</p>';}catch(error){$('routes').textContent=error.message;}}
 async function routeAction(button){const card=button.closest('[data-route]');button.disabled=true;try{await api(`/api/team/operations/routes/${card.dataset.route}/action`,{method:'POST',body:JSON.stringify({action:button.dataset.routeAction,stopId:button.dataset.stop||''})});await loadRoutes();}catch(error){$('message').textContent=error.message;button.disabled=false;}}
 const isoDate=date=>{const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,'0'),day=String(date.getDate()).padStart(2,'0');return `${year}-${month}-${day}`;};
 function renderAvailabilityCalendar(){
  const year=availabilityMonth.getFullYear(),month=availabilityMonth.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),offset=(first.getDay()+6)%7,today=isoDate(new Date());
  $('availabilityMonthLabel').textContent=new Intl.DateTimeFormat('nl-NL',{month:'long',year:'numeric'}).format(first);
  $('availabilityPreviousMonth').disabled=year===new Date().getFullYear()&&month===new Date().getMonth();
  const cells=Array(offset).fill('<span class="availability-empty"></span>');
  for(let day=1;day<=days;day+=1){const date=isoDate(new Date(year,month,day)),entry=availabilityEntries.get(date),past=date<today,label=entry?.preference==='preferred'?'Voorkeur':entry?.preference==='available'?'Beschikbaar':entry?.preference==='unavailable'?'Niet beschikbaar':'';cells.push(`<button type="button" class="availability-day${entry?' has-choice':''}${entry?.preference?` is-${entry.preference}`:''}${activeAvailabilityDate===date?' is-selected':''}" data-date="${date}"${past?' disabled':''}><b>${day}</b>${label?`<small>${escape(label)}</small>`:''}${entry?.start_time&&entry?.end_time?`<em>${escape(entry.start_time)}–${escape(entry.end_time)}</em>`:''}</button>`);}
  $('availabilityDates').innerHTML=cells.join('');
 }
 function openAvailabilityDate(date){
  activeAvailabilityDate=date;const entry=availabilityEntries.get(date)||{preference:'available',start_time:'09:00',end_time:'17:00'},source=new Date(`${date}T12:00:00`),copyUntil=new Date(source.getFullYear(),source.getMonth()+1,0);availabilityEntries.set(date,entry);$('availabilityEditor').hidden=false;$('availabilityEditorDate').textContent=new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(source);$('availabilityPreference').value=entry.preference;$('availabilityStart').value=entry.start_time||'';$('availabilityEnd').value=entry.end_time||'';const disabled=entry.preference==='unavailable';$('availabilityStart').disabled=disabled;$('availabilityEnd').disabled=disabled;$('availabilityCopyUntil').min=date;$('availabilityCopyUntil').max=isoDate(new Date(source.getFullYear(),source.getMonth()+6,source.getDate()));$('availabilityCopyUntil').value=isoDate(copyUntil);document.querySelectorAll('.availability-copy-days input').forEach(input=>input.checked=Number(input.value)===source.getDay());$('availabilityCopyMessage').textContent='';renderAvailabilityCalendar();
 }
 function updateAvailabilityEditor(){if(!activeAvailabilityDate)return;const preference=$('availabilityPreference').value,unavailable=preference==='unavailable';$('availabilityStart').disabled=unavailable;$('availabilityEnd').disabled=unavailable;availabilityEntries.set(activeAvailabilityDate,{preference,start_time:unavailable?'':$('availabilityStart').value,end_time:unavailable?'':$('availabilityEnd').value});renderAvailabilityCalendar();}
 async function loadAvailability(){try{const result=await api('/api/team/operations/availability');availabilityEntries=new Map(result.dates.map(item=>[item.work_date,item]));activeAvailabilityDate='';$('availabilityEditor').hidden=true;renderAvailabilityCalendar();}catch(error){$('availabilityDates').textContent=error.message;}}
 async function loadHrm(){const result=await api('/api/team/hrm',{headers:{'X-HRM-PIN':hrmPin}}),p=result.profile||{},t=result.terms||{},tot=result.totals||{};$('hrmLock').hidden=true;$('hrmContent').hidden=false;$('hrmContent').innerHTML=`<div class="earnings"><span>Opgebouwde indicatie</span><strong>€ ${Number(tot.earnings||0).toLocaleString('nl-NL',{minimumFractionDigits:2})}</strong><small>${Math.round(Number(tot.seconds||0)/36)/100} uur · ${tot.items||0} items</small></div><div class="terms"><h3>Afspraken</h3><p>Vergoeding: ${t.payType==='item'?'per item':'per uur'}<br>Uurloon: € ${escape(t.hourlyRate||'—')} · Per item: € ${escape(t.itemRate||'—')}</p><details><summary>Contract / arbeidsvoorwaarden</summary><p>${escape(t.contract||'Nog niet vastgelegd.')}</p></details></div><form id="hrmProfile"><h3>Mijn gegevens</h3><label>Telefoon<input name="phone" value="${escape(p.phone||'')}"></label><label>E-mail<input type="email" name="email" value="${escape(p.email||'')}"></label><label>Adres<input name="address" value="${escape(p.address||'')}"></label><label>IBAN<input name="iban" value="${escape(p.iban||'')}"></label><button class="primary" type="submit">Gegevens opslaan</button></form>`;}
 $('loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;$('message').textContent='Aanmelden…';try{const session=await api('/api/team/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});token=session.token;sessionStorage.setItem('ls-team-session',token);event.target.reset();await load();$('message').textContent='';const value=new URLSearchParams(location.hash.replace(/^#/,'')).get('scan');if(value)openScan(value);}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}});
 $('tasks').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,card=form.closest('.task'),record=records.find(r=>r.reference===card.dataset.reference),message=form.querySelector('.task-status'),button=form.querySelector('button');button.disabled=true;try{const values=Object.fromEntries(new FormData(form)),result=await api('/api/team/tasks/'+encodeURIComponent(record.reference),{method:'PATCH',body:JSON.stringify({...values,currentStep:Number(values.currentStep),revision:record.revision})});records=records.map(r=>r.reference===result.record.reference?result.record:r);render();}catch(error){message.textContent=error.message;button.disabled=false;}});
 document.querySelector('.staff-tabs').onclick=event=>{const button=event.target.closest('[data-tab]');if(button)setTab(button.dataset.tab);};$('manualScan').onsubmit=event=>{event.preventDefault();openScan(new FormData(event.target).get('scan'));};$('startScanner').onclick=toggleScanner;$('scanResult').onclick=event=>{const button=event.target.closest('[data-scan-action]');if(button)runScanAction(button);};$('routes').onclick=event=>{const button=event.target.closest('[data-route-action]');if(button)routeAction(button);};
 $('availabilityDates').onclick=event=>{const button=event.target.closest('[data-date]');if(button)openAvailabilityDate(button.dataset.date);};$('availabilityPreviousMonth').onclick=()=>{availabilityMonth=new Date(availabilityMonth.getFullYear(),availabilityMonth.getMonth()-1,1);renderAvailabilityCalendar();};$('availabilityNextMonth').onclick=()=>{availabilityMonth=new Date(availabilityMonth.getFullYear(),availabilityMonth.getMonth()+1,1);renderAvailabilityCalendar();};$('availabilityPreference').onchange=updateAvailabilityEditor;$('availabilityStart').onchange=updateAvailabilityEditor;$('availabilityEnd').onchange=updateAvailabilityEditor;$('availabilityCopy').onclick=()=>{if(!activeAvailabilityDate)return;updateAvailabilityEditor();const weekdays=new Set([...document.querySelectorAll('.availability-copy-days input:checked')].map(input=>Number(input.value))),until=$('availabilityCopyUntil').value,source=availabilityEntries.get(activeAvailabilityDate);if(!weekdays.size){$('availabilityCopyMessage').textContent='Kies minimaal één weekdag.';return;}if(!until||until<activeAvailabilityDate){$('availabilityCopyMessage').textContent='Kies een geldige einddatum.';return;}let copied=0,cursor=new Date(`${activeAvailabilityDate}T12:00:00`),limit=new Date(`${until}T12:00:00`);while(cursor<=limit&&copied<180){const date=isoDate(cursor);if(weekdays.has(cursor.getDay())){availabilityEntries.set(date,{...source});copied+=1;}cursor.setDate(cursor.getDate()+1);}$('availabilityCopyMessage').textContent=`Instelling overgenomen op ${copied} dag${copied===1?'':'en'}. Kies hieronder Opslaan.`;renderAvailabilityCalendar();};$('availabilityRemove').onclick=()=>{if(!activeAvailabilityDate)return;availabilityEntries.delete(activeAvailabilityDate);activeAvailabilityDate='';$('availabilityEditor').hidden=true;renderAvailabilityCalendar();};
 $('availabilityForm').onsubmit=async event=>{event.preventDefault();updateAvailabilityEditor();const dates=[...availabilityEntries.entries()].map(([date,item])=>({date,preference:item.preference,startTime:item.start_time||'',endTime:item.end_time||''}));try{await api('/api/team/operations/availability',{method:'PATCH',body:JSON.stringify({dates})});$('message').textContent='Beschikbaarheid en werktijden opgeslagen.';await loadAvailability();}catch(error){$('message').textContent=error.message;}};
 $('hrmSetupToggle').onclick=()=>{$('hrmSetup').hidden=!$('hrmSetup').hidden;};$('hrmSetup').onsubmit=async event=>{event.preventDefault();try{await api('/api/team/hrm/setup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});$('message').textContent='HRM-pincode ingesteld. Ontgrendel het tabblad.';$('hrmSetup').hidden=true;}catch(error){$('message').textContent=error.message;}};
 $('hrmUnlock').onsubmit=async event=>{event.preventDefault();hrmPin=String(new FormData(event.target).get('pin'));try{await loadHrm();event.target.reset();}catch(error){$('message').textContent=error.message;}};$('hrmContent').onsubmit=async event=>{if(event.target.id!=='hrmProfile')return;event.preventDefault();try{await api('/api/team/hrm',{method:'PATCH',headers:{'X-HRM-PIN':hrmPin},body:JSON.stringify({profile:Object.fromEntries(new FormData(event.target))})});$('message').textContent='Persoonsgegevens beveiligd opgeslagen.';}catch(error){$('message').textContent=error.message;}};
 $('refresh').onclick=async()=>{try{await load();$('message').textContent='';}catch(error){$('message').textContent=error.message;}};$('search').oninput=render;$('logout').onclick=async()=>{try{await api('/api/team/logout',{method:'POST'});}catch{}finally{clear();}};
 if(token)load().then(()=>{const value=new URLSearchParams(location.hash.replace(/^#/,'')).get('scan');if(value)openScan(value);}).catch(error=>{clear();$('message').textContent=error.message;});
})();
